import type { PlannerGuest, PlannerTable, SeatingPlan } from "@/lib/seating";

type DemoGuest = Omit<PlannerGuest, "tableId"> & { table?: string };

const demoTables: PlannerTable[] = [
  {
    id: "demo-mesa-1",
    name: "Mesa 1 · Familia de Cristina",
    capacity: 10,
    shape: "round",
  },
  {
    id: "demo-mesa-2",
    name: "Mesa 2 · Familia de Miguel",
    capacity: 10,
    shape: "round",
  },
  {
    id: "demo-mesa-3",
    name: "Mesa 3 · Instituto",
    capacity: 8,
    shape: "rectangular",
  },
  {
    id: "demo-mesa-4",
    name: "Mesa 4 · Universidad",
    capacity: 8,
    shape: "rectangular",
  },
  {
    id: "demo-mesa-5",
    name: "Mesa 5 · Trabajo de Cristina",
    capacity: 8,
    shape: "round",
  },
  {
    id: "demo-mesa-6",
    name: "Mesa 6 · Trabajo de Miguel",
    capacity: 8,
    shape: "round",
  },
  {
    id: "demo-mesa-7",
    name: "Mesa 7 · Peques",
    capacity: 6,
    shape: "rectangular",
  },
];

const demoGuests: DemoGuest[] = [
  {
    id: "demo-1",
    name: "Cristina",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Novia",
    isChild: false,
    group: "Novios",
    table: "demo-mesa-1",
  },
  {
    id: "demo-2",
    name: "Miguel",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Novio",
    isChild: false,
    group: "Novios",
    table: "demo-mesa-1",
  },
  {
    id: "demo-3",
    name: "Pilar Vidal",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Familia de Cristina",
    table: "demo-mesa-1",
  },
  {
    id: "demo-4",
    name: "Andrés Vidal",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Familia de Cristina",
    table: "demo-mesa-1",
  },
  {
    id: "demo-5",
    name: "Lucía Vidal",
    attendance: "confirmed",
    dietaryRestrictions: "vegetariana",
    allergies: "frutos secos",
    notes: "Revisar postre sin frutos secos",
    isChild: false,
    group: "Familia de Cristina",
    table: "demo-mesa-1",
  },
  {
    id: "demo-6",
    name: "Sofía Vidal",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Necesita trona",
    isChild: true,
    group: "Familia de Cristina",
    table: "demo-mesa-7",
  },
  {
    id: "demo-7",
    name: "Carmen Ruiz",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Familia de Cristina",
    table: "demo-mesa-1",
  },
  {
    id: "demo-8",
    name: "Javier Vidal",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Trae el coche para el tío Emilio",
    isChild: false,
    group: "Familia de Cristina",
    table: "demo-mesa-1",
  },
  {
    id: "demo-9",
    name: "Rosa Delgado",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Familia de Miguel",
    table: "demo-mesa-2",
  },
  {
    id: "demo-10",
    name: "Antonio Morales",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Familia de Miguel",
    table: "demo-mesa-2",
  },
  {
    id: "demo-11",
    name: "Elena Morales",
    attendance: "confirmed",
    dietaryRestrictions: "sin gluten",
    allergies: "",
    notes: "Menú celiaquía confirmado con el restaurante",
    isChild: false,
    group: "Familia de Miguel",
    table: "demo-mesa-2",
  },
  {
    id: "demo-12",
    name: "Paco Morales",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "marisco",
    notes: "",
    isChild: false,
    group: "Familia de Miguel",
    table: "demo-mesa-2",
  },
  {
    id: "demo-13",
    name: "Abuela Carmen",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Cerquita de los novios, evita corriente de aire",
    isChild: false,
    group: "Familia de Miguel",
    table: "demo-mesa-2",
  },
  {
    id: "demo-14",
    name: "Laura Sanchís",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Instituto",
    table: "demo-mesa-3",
  },
  {
    id: "demo-15",
    name: "Nacho Ferrer",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Instituto",
    table: "demo-mesa-3",
  },
  {
    id: "demo-16",
    name: "Bea Ortiz",
    attendance: "confirmed",
    dietaryRestrictions: "vegana",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Instituto",
    table: "demo-mesa-3",
  },
  {
    id: "demo-17",
    name: "Guille Ríos",
    attendance: "pending",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Ha dicho que casi seguro que sí",
    isChild: false,
    group: "Instituto",
    table: "demo-mesa-3",
  },
  {
    id: "demo-18",
    name: "Irene Castillo",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Instituto",
  },
  {
    id: "demo-19",
    name: "Dani Prats",
    attendance: "declined",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Se va de viaje ese finde",
    isChild: false,
    group: "Instituto",
  },
  {
    id: "demo-20",
    name: "Marta Puig",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Universidad",
    table: "demo-mesa-4",
  },
  {
    id: "demo-21",
    name: "Álex Bermejo",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Universidad",
    table: "demo-mesa-4",
  },
  {
    id: "demo-22",
    name: "Sara Llorens",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "lactosa",
    notes: "",
    isChild: false,
    group: "Universidad",
    table: "demo-mesa-4",
  },
  {
    id: "demo-23",
    name: "Kevin Martín",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Universidad",
    table: "demo-mesa-4",
  },
  {
    id: "demo-24",
    name: "Tania Gil",
    attendance: "pending",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Universidad",
  },
  {
    id: "demo-25",
    name: "Rubén Sancho",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Universidad",
  },
  {
    id: "demo-26",
    name: "Clara Ibáñez",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Cristina",
    table: "demo-mesa-5",
  },
  {
    id: "demo-27",
    name: "Óscar Ledesma",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Cristina",
    table: "demo-mesa-5",
  },
  {
    id: "demo-28",
    name: "Rocío Vega",
    attendance: "confirmed",
    dietaryRestrictions: "vegetariana",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Cristina",
    table: "demo-mesa-5",
  },
  {
    id: "demo-29",
    name: "Miguel Ángel Sáez",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Cristina",
    table: "demo-mesa-5",
  },
  {
    id: "demo-30",
    name: "Paula Cifuentes",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Llega después del postre",
    isChild: false,
    group: "Trabajo de Cristina",
    table: "demo-mesa-5",
  },
  {
    id: "demo-31",
    name: "Sergio Blanco",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Miguel",
    table: "demo-mesa-6",
  },
  {
    id: "demo-32",
    name: "Nuria Acosta",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Miguel",
    table: "demo-mesa-6",
  },
  {
    id: "demo-33",
    name: "Tomás Herrera",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Miguel",
    table: "demo-mesa-6",
  },
  {
    id: "demo-34",
    name: "Vera Domínguez",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Trabajo de Miguel",
    table: "demo-mesa-6",
  },
  {
    id: "demo-35",
    name: "Leo Serrano",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: true,
    group: "Peques",
    table: "demo-mesa-7",
  },
  {
    id: "demo-36",
    name: "Coco Serrano",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Hermano de Leo, 4 años",
    isChild: true,
    group: "Peques",
    table: "demo-mesa-7",
  },
  {
    id: "demo-37",
    name: "Jimena Cruz",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: true,
    group: "Peques",
    table: "demo-mesa-7",
  },
  {
    id: "demo-38",
    name: "Mateo Aguilar",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: true,
    group: "Peques",
  },
  {
    id: "demo-39",
    name: "Tía Charo",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "Prefiere silla con respaldo",
    isChild: false,
    group: "Familia de Miguel",
  },
  {
    id: "demo-40",
    name: "Juan Pedro Delgado",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Familia de Cristina",
  },
  {
    id: "demo-41",
    name: "Ana Ferrán",
    attendance: "confirmed",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Vecinos de Alcalá",
  },
  {
    id: "demo-42",
    name: "Luis Ferrán",
    attendance: "pending",
    dietaryRestrictions: "",
    allergies: "",
    notes: "",
    isChild: false,
    group: "Vecinos de Alcalá",
  },
];

export function demoPlan(): SeatingPlan {
  return {
    version: 1,
    name: "Plan de ejemplo · Cristina y Miguel",
    guests: demoGuests.map(
      ({ table, ...guest }: DemoGuest): PlannerGuest => ({
        ...guest,
        tableId: table ?? null,
      }),
    ),
    tables: demoTables,
  };
}
